### ISSUE TITLE
Добавить документ по работе с координаторами

### ISSUE THREAD

**Issue by ismetanin** [surfstudio/Surf-iOS-Developers#14]
Нужно описать подходы по работе с координаторами в рамках Surf MVP

**Comment by gregoryvit** [comment]
@alexfilimon @fixique Нужно договорится, кто будет про координаторы раздел делать

**Comment by fixique** [comment]
@alexfilimon @gregoryvit Обсуждали вроде с Гришей, что Саша делает что-то отличное от моего. Поэтому думал, что я делаю.
