### ISSUE TITLE
Перенести описание тестового задания

### ISSUE THREAD

**Issue by gregoryvit** [surfstudio/Surf-iOS-Developers#21]
Перенести в этот репозиторий описание тестового задания для стажеров Surf из Google Docs https://docs.google.com/document/d/1o-SPvzBJSTYAdbDodLNr03ojjt_w4PB3wn5opXQN17g/edit

**Comment by gregoryvit** [comment]
@avsmirnov567 отдадим @fixique эту задачку?)

**Comment by avsmirnov567** [comment]
да, конечно, забирайте

**Comment by chausovSurfStudio** [comment]
было сделано
