### ISSUE TITLE
Перенести список полезных материалов для начинающих разработчиков

### ISSUE THREAD

**Issue by gregoryvit** [surfstudio/Surf-iOS-Developers#22]
Сейчас список материалов есть в Google Docs (https://docs.google.com/document/d/1fLa-eR2-pyCXU32Anb6Wx3X6of-tBuGMh4bGrC2oI3U/edit) и Confluence.
Нужно актуализировать его и перенести сюда

**Comment by fixique** [comment]
Еще очень много полезного в репозиториях летних школ. Стоит обратить внимание на их материалы.

**Comment by chausovSurfStudio** [comment]
было реализовано
