### ISSUE TITLE
Поднять вверх раздел Best Practices

### ISSUE THREAD

**Issue by ismetanin** [surfstudio/Surf-iOS-Developers#8]
Предлагаю вынести вверх Best Practices, а Pods перенести в отдельную директорию, на которую сослаться с Best Practices
Почему? Потому что Best Practices это как раз основной раздел на мой взгляд, который должен быть первым на глазах

**Comment by LastSprint** [comment]
Мммм, я не согласен. Потому что во-первых это репозиторий-агрегатор. Да и какая разница, если в самом верху у нас содержание (или оглавление)

**Comment by gregoryvit** [comment]
Если идейно, то репозиторий задумывался как единая точка входа для знакомства с тем как мы работаем в студии → не уместно список библиотек наверх помещать. 

Предлагаю его поднять после того как раздел с практиками заполнится. Сейчас поднимать сомнительно, так как он меньше полезности представляет чем раздел с библиотеками.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LastSprint** [comment]
Но это же не список абстрактных библиотек. Это список библиотек которые мы разрабатываем и поддерживаем. И опять же - вверху оглавление

**Comment by ismetanin** [comment]
Может напишем какое-то хорошее введение и после него начнем ссылаться на код-стайл/архитектуру/кодогенерацию/инициализацию проектов (хотя насчет последних двух не уверен, что это должно быть самым важным, так что можем на это сделать меньше акцент), а потом уже пойдет раздел Pods.

Я считаю, что пока что из того что у нас есть, самое важное для разработчика это код стайл + архитектура

**Comment by chausovSurfStudio** [comment]
не актуально более, закрываем
